-- Seed: Simulations (corrected column names)
INSERT INTO liceu_simulations (module_id, title, scenario_markdown, simulation_constraint, success_criteria, simulation_type, related_lessons, rhetorical_dimensions, archetype_keys, difficulty_tier, estimated_minutes, is_published) VALUES
('b379baec-20a7-4c1f-baba-c75131143f99', 'Apresentação sob pressão',
'Você tem 5 minutos para apresentar um projeto urgente ao diretor que sempre desconfia de propostas. Ele já interrompeu duas apresentações hoje.',
'Tempo: 5 minutos. Audiência: crítica e antecipada. Objetivo: convencê-la a liberar orçamento.',
'{"criteria": ["argumenta com clareza (3 pontos)", "usa dados concretos", "trata objeções com verossimilhança", "finaliza com call-to-action específico"]}',
'hostile_interruption',
ARRAY['7fb64976-d532-4445-ba07-fb09754b068d'::uuid],
ARRAY['pronuntiatio'],
ARRAY['orador'],
4, 5, true),

('b379baec-20a7-4c1f-baba-c75131143f99', 'Resposta a objeção em público',
'Em uma reunião de 20 pessoas, um colega questiona sua metodologia: "Isso parece muito teórico, não é?"',
'Tempo: 30 segundos para responder. Audiência: colegiados. Objetivo: desarmar sem atacar.',
'{"criteria": ["reconhece a preocupação (ethos)", "conecta à prática (exemplo)", "redireciona (call-to-action)"]}',
'improvised_objection',
ARRAY['7fb64976-d532-4445-ba07-fb09754b068d'::uuid],
ARRAY['pronuntiatio'],
ARRAY['orador'],
3, 1, true),

('b379baec-20a7-4c1f-baba-c75131143f99', 'Defesa de posição impopular',
'Você precisa defender a ideia de cortar um recurso popular porque é ineficiente.',
'Tempo: 2 minutos. Restrição: não pode usar dados (não tem acesso). Objetivo: convencer sem autoridade externa.',
'{"criteria": ["usa valores compartilhados (ethos)", "apela para consequências (pathos)", "oferece alternativa (logos)"]}',
'unpopular_position',
ARRAY['7fb64976-d532-4445-ba07-fb09754b068d'::uuid],
ARRAY['pronuntiatio'],
ARRAY['orador'],
4, 2, true),

('b379baec-20a7-4c1f-baba-c75131143f99', 'Discurso sem preparo',
'Você é chamado para substituir um palestrante que não pôde comparecer. Tem 10 minutos de preparo.',
'Tempo: 10 minutos de preparo + 15 minutos de discurso. Restrição: não conhece a audiência. Objetivo: entregar valor.',
'{"criteria": ["usa estrutura clássica", "foca em 3 pontos universais", "adapta linguagem ao contexto"]}',
'hostile_interruption',
ARRAY['7fb64976-d532-4445-ba07-fb09754b068d'::uuid],
ARRAY['pronuntiatio'],
ARRAY['orador'],
5, 15, true);
